### ISSUE TITLE
graphql-dotnet server and reaact-apollo client side.

### ISSUE THREAD

**Issue by Perumal1201** [sagar-ganatra/graphql-express-relay#1]
Hello sir 
https://dzone.com/articles/on-graphql-and-building-an-application-using-react

The above link is awesome, In this repo i could not find the graphql-dotnet server. can you please share the graphql-dotnet server with react-apollo client.

**Comment by sagar-ganatra** [comment]
@Perumal1201 I'm not using a dotnet server instead I'm using NodeJS

**Comment by Perumal1201** [comment]
@sagar-ganatra ok.
